const isProd = process.env.NODE_ENV === "production";
const basePath = isProd ? "" : ""; // Adjust the base path for production

export const ImagePaths = {
  redGradientBg: `${basePath}/assets/img/bgImages/gradient-bg.jpg`, // background Images
  blackShadeImage: `${basePath}/assets/img/bgImages/black-shade.jpg`,
  groupImg: `${basePath}/assets/img/bgImages/faculty-bg.jpg`,
  mppImg: `${basePath}/assets/img/bgImages/masters_banner.jpg`,
  whiteShadeImg: `${basePath}/assets/img/bgImages/studentmix-banner.jpg`,

  governWhiteShadeImg: `${basePath}/assets/img/events/govtExcellenceInitivies/contact_bg.jpg`, // events inner pages background Images
  ppforpgImg: `${basePath}/assets/img/events/publicPolicy/ppforpg.jpg`,
  policyMaking: `${basePath}/assets/img/events/publicPolicy/policy_making.jpg`,
  mppApplication: `${basePath}/assets/img/events/publicPolicy/mpp_application.jpg`,
  masterMpp: `${basePath}/assets/img/events/publicPolicy/masterMPP.jpg`,
  infoSession: `${basePath}/assets/img/events/publicPolicy/info_session_bg.png`,
  footerBg: `${basePath}/assets/img/events/publicPolicy/footer_bg.png`,
  braveBg: `${basePath}/assets/img/events/publicPolicy/brave_bg.jpg`,
  childrenPolicy: `${basePath}/assets/img/events/publicPolicy/children_bg.jpg`,
  climatePolicy: `${basePath}/assets/img/events/publicPolicy/climate_bg.jpg`,
  climateTextPolicy: `${basePath}/assets/img/events/publicPolicy/3-a.jpg`,

  aluminiBg: `${basePath}/assets/img/events/alumni/alumini_bg.jpg`,
  aluminiMidBg: `${basePath}/assets/img/events/alumni/alumini_middle_bg.jpg`,
  aluminiSpeakerBg: `${basePath}/assets/img/events/alumni/alumini_speaker.jpg`,

  novFooter: `${basePath}/assets/img/talkseries/talkpolicy/november_footer_bg.jpg`,
  novBg: `${basePath}/assets/img/talkseries/talkpolicy/november_bg.jpg`,
  fiveBg: `${basePath}/assets/img/talkseries/talkpolicy/5g_bg.jpg`,
  fiveSepBg: `${basePath}/assets/img/talkseries/talkpolicy/5g_spe_bg.jpg`,
  currBg: `${basePath}/assets/img/talkseries/talkpolicy/curr_bg.jpg`,
  currFooterBg: `${basePath}/assets/img/talkseries/talkpolicy/curr_footer_bg.jpg`,
  aiBg: `${basePath}/assets/img/talkseries/talkpolicy/ai_bg.jpg`,
  budgetBg: `${basePath}/assets/img/talkseries/talkpolicy/budget_bg.jpg`,
  budgetMidBg: `${basePath}/assets/img/talkseries/talkpolicy/budget_middle_bg.jpg`,
  multiLateral: `${basePath}/assets/img/talkseries/talkpolicy/multilateral_bg.jpg`,
  multiLateralSep: `${basePath}/assets/img/talkseries/talkpolicy/multilateral_spe_bg.jpg`,
  multiFooter: `${basePath}/assets/img/talkseries/talkpolicy/multilateral_footer.jpg`,
  uniteDivide: `${basePath}/assets/img/talkseries/talkpolicy/uniteDivide.jpg`,
  uniteDivideMid: `${basePath}/assets/img/talkseries/talkpolicy/uniteDivide_middle_bg.jpg`,
  unPackingBg: `${basePath}/assets/img/talkseries/talkpolicy/unpacking_bg.jpg`,
  unPackingBgMid: `${basePath}/assets/img/talkseries/talkpolicy/unpacking_middle_bg.jpg`,
  cryptoBg: `${basePath}/assets/img/talkseries/talkpolicy/crypto_bg.jpg`,
  cryptoMidBg: `${basePath}/assets/img/talkseries/talkpolicy/crypto_middle_bg.jpg`,
  ecoOutlook: `${basePath}/assets/img/talkseries/talkpolicy/economic_outlook_bg.jpg`,
  globalBg: `${basePath}/assets/img/talkseries/talkpolicy/global_bg.jpg`,
  fitnessBg: `${basePath}/assets/img/talkseries/talkpolicy/fitness_bg.jpg`,
  talkPolicyBg: `${basePath}/assets/img/talkseries/talkpolicy/talk_policy_bg.jpg`,
  workForceBg: `${basePath}/assets/img/talkseries/talkpolicy/workforce_img.jpg`,
  workForceMidBg: `${basePath}/assets/img/talkseries/talkpolicy/workforce_middle_img.jpg`,
  railwayBg: `${basePath}/assets/img/talkseries/talkpolicy/railway_bg.jpg`,
  railwayMidBg: `${basePath}/assets/img/talkseries/talkpolicy/middlerailway_bg.jpg`,
  shapeBg: `${basePath}/assets/img/talkseries/talkpolicy/shapeup_bg.jpg`,
  shapePanaListBg: `${basePath}/assets/img/talkseries/talkpolicy/sahpe_panalist.jpg`,
  shapeMidBg: `${basePath}/assets/img/talkseries/talkpolicy/shape_middle_bg.jpg`,
  paksitanBg: `${basePath}/assets/img/talkseries/talkpolicy/pakistan_bg.jpg`,
  economicBg: `${basePath}/assets/img/talkseries/talkpolicy/economic_bg.jpg`,
  economicMiddleBg: `${basePath}/assets/img/talkseries/talkpolicy/economic_middle_bg.jpg`,
  russiaBg: `${basePath}/assets/img/talkseries/talkpolicy/r_bg.jpg`,
  russiaSepBg: `${basePath}/assets/img/talkseries/talkpolicy/r_sep_bg.jpg`,
  russiaFooterBg: `${basePath}/assets/img/talkseries/talkpolicy/r_footer_bg.jpg`,

  playOutlook: `${basePath}/assets/img/talkseries/publicpolicy/playoutlook_bg.jpg`,
  careerBg: `${basePath}/assets/img/talkseries/publicpolicy/career_bg.jpg`,
  impactFooterBg: `${basePath}/assets/img/talkseries/publicpolicy/impact_footer_bg.jpg`,
  politicalBg: `${basePath}/assets/img/talkseries/publicpolicy/political_bg.jpg`,
  impactBg: `${basePath}/assets/img/talkseries/publicpolicy/impact_bg.jpg`,
  masterPubilc: `${basePath}/assets/img/talkseries/publicpolicy/MasterInPublicPolicy_bg.jpg`,

  syed: `${basePath}/assets/img/blogs/syed.jpg`, // images

  redArrow: `${basePath}/assets/img/iconimages/redarrow.png`,
  geiAug1: `${basePath}/assets/img/events/govtExcellenceInitivies/gei_aug_2023_1.jpg`, // governance event page
  geiAug2: `${basePath}/assets/img/events/govtExcellenceInitivies/gei_aug_2023_2.jpg`,
  geiDec1: `${basePath}/assets/img/events/govtExcellenceInitivies/gei_dec_2022_1.jpg`,
  geiDec2: `${basePath}/assets/img/events/govtExcellenceInitivies/gei_dec_2022_2.jpg`,
  geiJul: `${basePath}/assets/img/events/govtExcellenceInitivies/gei_july_2023.jpg`,
  geiJul2: `${basePath}/assets/img/events/govtExcellenceInitivies/gei_july_2023_2.jpg`,
  geiMay: `${basePath}/assets/img/events/govtExcellenceInitivies/gei_may_2024_1.jpg`,
  geiMay2: `${basePath}/assets/img/events/govtExcellenceInitivies/gei_may_2024_2.jpg`,

  colloqy1: `${basePath}/assets/img/colluquy/kc-colloquy-1.jpeg`, // colloqy
  colloqy2: `${basePath}/assets/img/colluquy/kc-colloquy-2.jpeg`,
  colloqy3: `${basePath}/assets/img/colluquy/kc-colloquy-3.jpeg`,
  colloqy4: `${basePath}/assets/img/colluquy/kc-colloquy-4.jpeg`,

  quote: `${basePath}/assets/img/talkseries/talkpolicy/quote.png`, // let talk policy
  quoteRed4Sep: `${basePath}/assets/img/talkseries/talkpolicy/quote_red.png`, // let talk policy
  calenderWhite: `${basePath}/assets/img/talkseries/talkpolicy/calender_white.png`,
  timeWhite: `${basePath}/assets/img/talkseries/talkpolicy/time_white.png`,
  calenderTime: `${basePath}/assets/img/talkseries/talkpolicy/Calender_time.png`,

  LPTopBanner: `${basePath}/assets/img/talkseries/talkpolicy/LP-top-banner-PNG-1.png`,
  LPTopBanner1: `${basePath}/assets/img/talkseries/talkpolicy/LP-top-banner-PNG-1-1.png`,

  LPBanner: `${basePath}/assets/img/talkseries/talkpolicy/Banner_LP.png`,
  banner: `${basePath}/assets/img/talkseries/talkpolicy/Banner.png`,

  ficciLogo: `${basePath}/assets/img/talkseries/talkpolicy/Ficci-Logo.png`,

  img11: `${basePath}/assets/img/talkseries/talkpolicy/img-11.png`,
  img1: `${basePath}/assets/img/talkseries/talkpolicy/1-1.png`,
  img2: `${basePath}/assets/img/talkseries/talkpolicy/2-2.png`,
  img3: `${basePath}/assets/img/talkseries/talkpolicy/3-3.png`,
  img4: `${basePath}/assets/img/talkseries/talkpolicy/4-2.png`,

  socialTwitter: `${basePath}/assets/img/talkseries/talkpolicy/social_twitter.png`,
  socialFacebook: `${basePath}/assets/img/talkseries/talkpolicy/social_facebook.png`,
  socialYoutube: `${basePath}/assets/img/talkseries/talkpolicy/social_youtube.jpg`,

  Amar: `${basePath}/assets/img/talkseries/talkpolicy/Amar.jpg`,
  nikhil: `${basePath}/assets/img/talkseries/talkpolicy/Nikhil.jpg`,
  mishi: `${basePath}/assets/img/talkseries/talkpolicy/Mishi.jpg`,

  Nidi: `${basePath}/assets/img/talkseries/talkpolicy/Nidi.png`,
  Nidhi: `${basePath}/assets/img/talkseries/talkpolicy/Nidhi.png`,
  Navtej: `${basePath}/assets/img/talkseries/talkpolicy/Navtej1.png`,
  Suhasini: `${basePath}/assets/img/talkseries/talkpolicy/Suhasini.png`,
  Amitabh: `${basePath}/assets/img/talkseries/talkpolicy/Amitabh.png`,
  Shanthie: `${basePath}/assets/img/talkseries/talkpolicy/Shanthie.png`,
  prashant: `${basePath}/assets/img/talkseries/talkpolicy/5g_prashant.png`,
  puru: `${basePath}/assets/img/talkseries/talkpolicy/5g_puru.png`,
  nazeer: `${basePath}/assets/img/talkseries/talkpolicy/5g_nazeer.png`,
  smita: `${basePath}/assets/img/talkseries/talkpolicy/5g_smita.png`,
  dilipChenoy: `${basePath}/assets/img/talkseries/talkpolicy/Dilip-Chenoy_circle.png`,
  pande: `${basePath}/assets/img/talkseries/talkpolicy/Jyoti_Pande_Lavakare.png`,
  krishna: `${basePath}/assets/img/talkseries/talkpolicy/Bhargav_Krishna.png`,
  Krishna: `${basePath}/assets/img/talkseries/talkpolicy/Krishna.png`,
  rajat: `${basePath}/assets/img/talkseries/talkpolicy/Rajat.png`,
  vinod: `${basePath}/assets/img/talkseries/talkpolicy/vinod.jpg`,
  mitali: `${basePath}/assets/img/talkseries/talkpolicy/mitali.jpg`,
  venu: `${basePath}/assets/img/talkseries/talkpolicy/venu.jpg`,
  smita: `${basePath}/assets/img/talkseries/talkpolicy/smita_sharma.jpg`,
  mSyed: `${basePath}/assets/img/talkseries/talkpolicy/m_syed.png`,
  mSaran: `${basePath}/assets/img/talkseries/talkpolicy/m_saran.png`,
  mManika: `${basePath}/assets/img/talkseries/talkpolicy/m_manika.png`,
  u1: `${basePath}/assets/img/talkseries/talkpolicy/u1.png`,
  u2: `${basePath}/assets/img/talkseries/talkpolicy/u2.png`,
  u3: `${basePath}/assets/img/talkseries/talkpolicy/u3.png`,
  u4: `${basePath}/assets/img/talkseries/talkpolicy/u4.png`,
  talkOne: `${basePath}/assets/img/talkseries/talkpolicy/1.png`,
  talkTwo: `${basePath}/assets/img/talkseries/talkpolicy/2.png`,
  talkThree: `${basePath}/assets/img/talkseries/talkpolicy/3.png`,
  talkFour: `${basePath}/assets/img/talkseries/talkpolicy/4.png`,
  speakersBg: `${basePath}/assets/img/talkseries/talkpolicy/speakers_bg.jpg`,
  rSyed: `${basePath}/assets/img/talkseries/talkpolicy/r_syed.png`,
  rVenkatesh: `${basePath}/assets/img/talkseries/talkpolicy/r_venkatesh.png`,

  sangita: `${basePath}/assets/img/talkseries/talkpolicy/Dr.-Sangita-Redy_circle.png`,
  lalKidwai: `${basePath}/assets/img/talkseries/talkpolicy/Naina-Lal-Kidwai.png`,
  nidhiRazdan: `${basePath}/assets/img/talkseries/talkpolicy/Nidhi-Razdan.png`,
  Pranesh: `${basePath}/assets/img/talkseries/talkpolicy/Pranesh-Prakash.png`,
  jiten: `${basePath}/assets/img/talkseries/talkpolicy/Jiten-Jain.png`,
  trisha: `${basePath}/assets/img/talkseries/talkpolicy/Trisha-Ray.png`,
  milind: `${basePath}/assets/img/talkseries/talkpolicy/Milind.png`,
  gupta: `${basePath}/assets/img/talkseries/talkpolicy/gupta.png`,
  prasanth: `${basePath}/assets/img/talkseries/talkpolicy/prasanth.png`,
  muktesh: `${basePath}/assets/img/talkseries/talkpolicy/muktesh.png`,
  smitaM: `${basePath}/assets/img/talkseries/talkpolicy/smita_m.png`,
  zaki: `${basePath}/assets/img/talkseries/talkpolicy/zaki.jpg`,
  prashant: `${basePath}/assets/img/talkseries/talkpolicy/prashant.jpg`,
  meghna: `${basePath}/assets/img/talkseries/talkpolicy/meghna.jpg`,
  cryptoSmita: `${basePath}/assets/img/talkseries/talkpolicy/crypto_smita.jpg`,
  Manish: `${basePath}/assets/img/talkseries/talkpolicy/Manisha.jpg`,
  Anita: `${basePath}/assets/img/talkseries/talkpolicy/Anita.jpg`,
  ambrish: `${basePath}/assets/img/talkseries/talkpolicy/ambrish.png`,
  arvind: `${basePath}/assets/img/talkseries/talkpolicy/arvind.png`,
  mithal: `${basePath}/assets/img/talkseries/talkpolicy/mithal.png`,
  f1: `${basePath}/assets/img/talkseries/talkpolicy/f1.png`,
  lisa: `${basePath}/assets/img/talkseries/talkpolicy/Lisa.png`,
  Navtej: `${basePath}/assets/img/talkseries/talkpolicy/Navtej.png`,
  Smita: `${basePath}/assets/img/talkseries/talkpolicy/Smita.png`,
  vasudha: `${basePath}/assets/img/talkseries/talkpolicy/vasudha.png`,
  shaili: `${basePath}/assets/img/talkseries/talkpolicy/shaili.png`,
  mahesh: `${basePath}/assets/img/talkseries/talkpolicy/mahesh.png`,
  nidhiRaz: `${basePath}/assets/img/talkseries/talkpolicy/nidhi_raz.png`,
  MaheshMangal: `${basePath}/assets/img/talkseries/talkpolicy/Mahesh-Mangal.jpg`,
  AlokVerma: `${basePath}/assets/img/talkseries/talkpolicy/Alok-Verma.jpg`,
  pannel1: `${basePath}/assets/img/talkseries/talkpolicy/pannel1.png`,
  steve: `${basePath}/assets/img/talkseries/talkpolicy/steve.png`,
  ashutosh: `${basePath}/assets/img/talkseries/talkpolicy/ashutosh.png`,
  vasuSingh: `${basePath}/assets/img/talkseries/talkpolicy/vasu_singh.png`,
  shapeSmita: `${basePath}/assets/img/talkseries/talkpolicy/shape_smita.png`,

  manisha: `${basePath}/assets/img/events/publicpolicy/Manish.png`,
  namita: `${basePath}/assets/img/events/publicpolicy/Namita.png`,
  anitaBhatia: `${basePath}/assets/img/events/publicpolicy/Anita-Bhatia.png`,
  sowmya: `${basePath}/assets/img/events/publicpolicy/sowmya.png`,
  anitha: `${basePath}/assets/img/events/publicpolicy/anitha.png`,
  one: `${basePath}/assets/img/events/publicpolicy/1.png`,
  two: `${basePath}/assets/img/events/publicpolicy/2.png`,
  emerging: `${basePath}/assets/img/events/publicpolicy/emerging.png`,
  askMeAny: `${basePath}/assets/img/events/publicpolicy/ask-me-any.png`,

  ask: `${basePath}/assets/img/talkseries/publicpolicy/ask.jpg`,
  dean: `${basePath}/assets/img/talkseries/publicpolicy/Dean.jpg`,
  image1: `${basePath}/assets/img/talkseries/publicpolicy/image1.jpg`,
  image2: `${basePath}/assets/img/talkseries/publicpolicy/image2.jpg`,
  image3: `${basePath}/assets/img/talkseries/publicpolicy/image3.jpg`,
  image4: `${basePath}/assets/img/talkseries/publicpolicy/image4.jpg`,
  image5: `${basePath}/assets/img/talkseries/publicpolicy/image5.jpg`,

  calenderRed: `${basePath}/assets/img/talkseries/publicpolicy/calender_red.png`,
  timeRed: `${basePath}/assets/img/talkseries/publicpolicy/time_red.png`,
  prateek: `${basePath}/assets/img/talkseries/publicpolicy/prateek.png`,
  seven: `${basePath}/assets/img/talkseries/publicpolicy/7.png`,
  eight: `${basePath}/assets/img/talkseries/publicpolicy/8.png`,
  nine: `${basePath}/assets/img/talkseries/publicpolicy/9.png`,
  nine: `${basePath}/assets/img/talkseries/publicpolicy/10.png`,
  PrateekKanwal: `${basePath}/assets/img/talkseries/publicpolicy/Prateek-Kanwal.png`,

  askMeWhite: `${basePath}/assets/img/events/alumni/ask-me-white.png`,
  calender: `${basePath}/assets/img/events/alumni/calender.png`,
  time: `${basePath}/assets/img/events/alumni/time.png`,
  alumini1: `${basePath}/assets/img/events/alumni/alumini1.png`,
  alumini2: `${basePath}/assets/img/events/alumni/alumini2.png`,
  alumini3: `${basePath}/assets/img/events/alumni/alumini3.png`,
  instagram: `${basePath}/assets/img/events/alumni/instagram.png`,
  twitter: `${basePath}/assets/img/events/alumni/twitter.png`,

  infoSessionLogo: `${basePath}/assets/img/events/publicpolicy/Info_Session_Logo.png`,
  mapRed: `${basePath}/assets/img/events/publicpolicy/map_red.png`,
  person1: `${basePath}/assets/img/events/publicpolicy/person1.png`,
  person2: `${basePath}/assets/img/events/publicpolicy/person2.png`,
  person3: `${basePath}/assets/img/events/publicpolicy/person3.png`,
  person4: `${basePath}/assets/img/events/publicpolicy/person4.png`,
  person5: `${basePath}/assets/img/events/publicpolicy/person5.png`,
  person6: `${basePath}/assets/img/events/publicpolicy/person6.png`,
  expect1: `${basePath}/assets/img/events/publicpolicy/expect1.png`,
  expect2: `${basePath}/assets/img/events/publicpolicy/expect2.png`,
  expect3: `${basePath}/assets/img/events/publicpolicy/expect3.png`,
  expect4: `${basePath}/assets/img/events/publicpolicy/expect4.png`,
  icontext1: `${basePath}/assets/img/events/publicpolicy/icontext1.png`,
  icontext2: `${basePath}/assets/img/events/publicpolicy/icontext2.png`,
  icontext3: `${basePath}/assets/img/events/publicpolicy/icontext3.png`,
  icontext4: `${basePath}/assets/img/events/publicpolicy/icontext4.png`,
  icontext5: `${basePath}/assets/img/events/publicpolicy/icontext5.png`,
  Icon: `${basePath}/assets/img/events/publicpolicy/Icon.png`,
  DeanAMA: `${basePath}/assets/img/events/publicpolicy/Dean-AMA-n.png`,
  dateIcon: `${basePath}/assets/img/events/publicpolicy/date-icon.png`,
  timeIcon: `${basePath}/assets/img/events/publicpolicy/time-icon.png`,
};
