const isProd = process.env.NODE_ENV === "production";
const basePath = isProd ? "/kautilya-next" : ""; // Adjust the base path for production

export const ImagePaths = {
  redGradientBg: `${basePath}/assets/img/bgImages/gradient-bg.jpg`,
  blackShadeImage: `${basePath}/assets/img/bgImages/black-shade.jpg`,
  groupImg: `${basePath}/assets/img/bgImages/faculty-bg.jpg`,
  mppImg: `${basePath}/assets/img/bgImages/masters_banner.jpg`,
  whiteShadeImg: `${basePath}/assets/img/bgImages/studentmix-banner.jpg`,

  governWhiteShadeImg: `${basePath}/assets/img/events/govtExcellenceInitivies/contact_bg.jpg`, // events inner pages
  ppforpgImg: `${basePath}/assets/img/events/publicPolicy/ppforpg.jpg`,
  policyMaking: `${basePath}/assets/img/events/publicPolicy/policy_making.jpg`,
  mppApplication: `${basePath}/assets/img/events/publicPolicy/mpp_application.jpg`,
  masterMpp: `${basePath}/assets/img/events/publicPolicy/masterMPP.jpg`,
  infoSession: `${basePath}/assets/img/events/publicPolicy/info_session_bg.png`,
  footerBg: `${basePath}/assets/img/events/publicPolicy/footer_bg.png`,
  braveBg: `${basePath}/assets/img/events/publicPolicy/brave_bg.jpg`,
  childrenPolicy: `${basePath}/assets/img/events/publicPolicy/children_bg.jpg`,
  climatePolicy: `${basePath}/assets/img/events/publicPolicy/climate_bg.jpg`,
  climateTextPolicy: `${basePath}/assets/img/events/publicPolicy/3-a.jpg`,

  aluminiBg: `${basePath}/assets/img/events/alumni/alumini_bg.jpg`,
  aluminiMidBg: `${basePath}/assets/img/events/alumni/alumini_middle_bg.jpg`,
  aluminiSpeakerBg: `${basePath}/assets/img/events/alumni/alumini_speaker.jpg`,

  novFooter: `${basePath}/assets/img/talkseries/talkpolicy/november_footer_bg.jpg`,
  novBg: `${basePath}/assets/img/talkseries/talkpolicy/november_bg.jpg`,
  fiveBg: `${basePath}/assets/img/talkseries/talkpolicy/5g_bg.jpg`,
  fiveSepBg: `${basePath}/assets/img/talkseries/talkpolicy/5g_spe_bg.jpg`,
  currBg: `${basePath}/assets/img/talkseries/talkpolicy/curr_bg.jpg`,
  currFooterBg: `${basePath}/assets/img/talkseries/talkpolicy/curr_footer_bg.jpg`,
  aiBg: `${basePath}/assets/img/talkseries/talkpolicy/ai_bg.jpg`,
  budgetBg: `${basePath}/assets/img/talkseries/talkpolicy/budget_bg.jpg`,
  budgetMidBg: `${basePath}/assets/img/talkseries/talkpolicy/budget_middle_bg.jpg`,
  multiLateral: `${basePath}/assets/img/talkseries/talkpolicy/multilateral_bg.jpg`,
  multiLateralSep: `${basePath}/assets/img/talkseries/talkpolicy/multilateral_spe_bg.jpg`,
  multiFooter: `${basePath}/assets/img/talkseries/talkpolicy/multilateral_footer.jpg`,
  uniteDivide: `${basePath}/assets/img/talkseries/talkpolicy/uniteDivide.jpg`,
  uniteDivideMid: `${basePath}/assets/img/talkseries/talkpolicy/uniteDivide_middle_bg.jpg`,
  unPackingBg: `${basePath}/assets/img/talkseries/talkpolicy/unpacking_bg.jpg`,
  unPackingBgMid: `${basePath}/assets/img/talkseries/talkpolicy/unpacking_middle_bg.jpg`,
  cryptoBg: `${basePath}/assets/img/talkseries/talkpolicy/crypto_bg.jpg`,
  cryptoMidBg: `${basePath}/assets/img/talkseries/talkpolicy/crypto_middle_bg.jpg`,
  ecoOutlook: `${basePath}/assets/img/talkseries/talkpolicy/economic_outlook_bg.jpg`,
  globalBg: `${basePath}/assets/img/talkseries/talkpolicy/global_bg.jpg`,
  fitnessBg: `${basePath}/assets/img/talkseries/talkpolicy/fitness_bg.jpg`,
  talkPolicyBg: `${basePath}/assets/img/talkseries/talkpolicy/talk_policy_bg.jpg`,
  workForceBg: `${basePath}/assets/img/talkseries/talkpolicy/workforce_img.jpg`,
  workForceMidBg: `${basePath}/assets/img/talkseries/talkpolicy/workforce_middle_img.jpg`,
  railwayBg: `${basePath}/assets/img/talkseries/talkpolicy/railway_bg.jpg`,
  railwayMidBg: `${basePath}/assets/img/talkseries/talkpolicy/middlerailway_bg.jpg`,
  shapeBg: `${basePath}/assets/img/talkseries/talkpolicy/shapeup_bg.jpg`,
  shapePanaListBg: `${basePath}/assets/img/talkseries/talkpolicy/sahpe_panalist.jpg`,
  shapeMidBg: `${basePath}/assets/img/talkseries/talkpolicy/shape_middle_bg.jpg`,
  paksitanBg: `${basePath}/assets/img/talkseries/talkpolicy/pakistan_bg.jpg`,
  economicBg: `${basePath}/assets/img/talkseries/talkpolicy/economic_bg.jpg`,
  economicMiddleBg: `${basePath}/assets/img/talkseries/talkpolicy/economic_middle_bg.jpg`,
  russiaBg: `${basePath}/assets/img/talkseries/talkpolicy/r_bg.jpg`,
  russiaSepBg: `${basePath}/assets/img/talkseries/talkpolicy/r_sep_bg.jpg`,
  russiaFooterBg: `${basePath}/assets/img/talkseries/talkpolicy/r_footer_bg.jpg`,

  playOutlook: `${basePath}/assets/img/talkseries/publicpolicy/playoutlook_bg.jpg`,
  careerBg: `${basePath}/assets/img/talkseries/publicpolicy/career_bg.jpg`,
  impactFooterBg: `${basePath}/assets/img/talkseries/publicpolicy/impact_footer_bg.jpg`,
  politicalBg: `${basePath}/assets/img/talkseries/publicpolicy/political_bg.jpg`,
  impactBg: `${basePath}/assets/img/talkseries/publicpolicy/impact_bg.jpg`,
  masterPubilc: `${basePath}/assets/img/talkseries/publicpolicy/MasterInPublicPolicy_bg.jpg`,
};
